//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSoftware.Core.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTSoftware.Core.Shared.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã hết hạn hoặc chưa được kích hoạt. Vui lòng thử lại sau.
        /// </summary>
        public static string ACCOUNT_EXPRIED_NEW {
            get {
                return ResourceManager.GetString("ACCOUNT_EXPRIED_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại. Vui lòng thử lại sau..
        /// </summary>
        public static string ACCOUNT_NOT_EXITS {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu không thành công.
        /// </summary>
        public static string CHANGE_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty bạn đã hết hợp đồng. Thêm hợp đồng mới để tiếp tục..
        /// </summary>
        public static string COMPANY_EXPRIED {
            get {
                return ResourceManager.GetString("COMPANY_EXPRIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty không tồn tại. Vui lòng thử lại sau..
        /// </summary>
        public static string COMPANY_NOT_EXITS {
            get {
                return ResourceManager.GetString("COMPANY_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty chưa đến hạn hợp đồng. Vui lòng quay lại sau..
        /// </summary>
        public static string COMPANY_NOT_READY {
            get {
                return ResourceManager.GetString("COMPANY_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền lên không đúng.
        /// </summary>
        public static string DATA_REQUEST_IN_VALID {
            get {
                return ResourceManager.GetString("DATA_REQUEST_IN_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình xử lý dữ liệu.
        /// </summary>
        public static string ERROR_ON_HANDLE_DATA {
            get {
                return ResourceManager.GetString("ERROR_ON_HANDLE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc của bạn đã hết hạn. Vui lòng đăng nhập lại.
        /// </summary>
        public static string EXPIRES_TOKEN {
            get {
                return ResourceManager.GetString("EXPIRES_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng thử lại sau.
        /// </summary>
        public static string HAS_ERROR {
            get {
                return ResourceManager.GetString("HAS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn phiên làm việc. Vui lòng thử lại sau..
        /// </summary>
        public static string INVALID_TOKEN_RESET {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn bị khóa tạm thời do đăng nhập sai quá nhiều. Vui lòng thử lại sau..
        /// </summary>
        public static string LOCK_ACCOUNT {
            get {
                return ResourceManager.GetString("LOCK_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người dùng không tồn tại.
        /// </summary>
        public static string NOT_EXIST_EMAIL {
            get {
                return ResourceManager.GetString("NOT_EXIST_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        public static string OLD_PASSWORD_INCORECT {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email thành công. .
        /// </summary>
        public static string SEND_MAIL_SUCCESS {
            get {
                return ResourceManager.GetString("SEND_MAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string SUCCEED {
            get {
                return ResourceManager.GetString("SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này..
        /// </summary>
        public static string UN_AUTHOZIRED {
            get {
                return ResourceManager.GetString("UN_AUTHOZIRED", resourceCulture);
            }
        }
    }
}
